version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: "pre-commit"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    groups:
      pre-commit-hooks:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: "rust-toolchain"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "cargo"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
