rules:
  unpinned-uses:
    config:
      policies:
        dtolnay/rust-toolchain: any
  excessive-permissions:
    # it's hard to test what the impact of removing these ignores would be
    # without actually running the release workflow...
    ignore:
      - release.yml

  use-trusted-publishing:
    ignore:
      - release.yml
