fail_fast: false

exclude:
  glob:
    - "*.svg"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        priority: 0
      - id: check-case-conflict
        priority: 0
      - id: check-merge-conflict
        priority: 0
      - id: check-symlinks
        priority: 0
      - id: check-yaml
        priority: 0
      - id: check-toml
        priority: 0
      - id: debug-statements
        priority: 0
      - id: end-of-file-fixer
        priority: 0
      - id: mixed-line-ending
        priority: 0
      - id: detect-private-key
        priority: 0

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
        priority: 0

  - repo: https://github.com/crate-ci/typos
    rev: v1.49.0
    hooks:
      - id: typos
        priority: 0

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        priority: 0

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.29.0
    hooks:
      - id: zizmor
        priority: 0

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.38.0
    hooks:
      - id: check-github-workflows
        priority: 0

  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        priority: 1

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.1
    hooks:
      - id: markdownlint-fix
        priority: 2

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
        args: ["--all-targets", "--all-features"]
        priority: 2
      - id: clippy
        args: ["--all-targets", "--all-features", "--", "-D", "warnings"]
        priority: 2

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false
        priority: 1

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        priority: 1
      - id: ruff-format
        priority: 1

  - repo: https://github.com/DevinR528/cargo-sort
    rev: v2.1.4
    hooks:
      - id: cargo-sort
        args: ["-g", "-w"]
        priority: 1
