site_name: GDSR
repo_url: https://github.com/gdsr/gdsr

nav:
  - User guide:
    - index.md
    - user-guide/getting-started.md
    - user-guide/installation.md
  - Python Api:
    - python-api/index.md
  - Development:
    - development/index.md
    - development/class_diagrams.md

theme:
  name: material
  locale: en
  palette:
      scheme: slate
      primary: teal
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

