site_name: GDSR
repo_url: https://github.com/gdsr/gdsr

nav:
  - User guide:
    - index.md
    - user-guide/getting-started.md
    - user-guide/installation.md
  - Python Api:
    - python-api/index.md
    - python-api/typing.md
    - Elements:
      - python-api/elements/array_reference.md
      - python-api/elements/box.md
      - python-api/elements/node.md
      - python-api/elements/path.md
      - python-api/elements/polygon.md
      - python-api/elements/reference.md
      - python-api/elements/text.md
  - Development:
    - development/index.md
    - development/class_diagrams.md

theme:
  name: material
  locale: en
  palette:
      scheme: slate
      primary: teal
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx 
            show_source: false
            find_stubs_package: true
            show_submodules: true