site_name: GDSR
repo_url: https://github.com/gdsr/gdsr

nav:
  - User guide:
      - index.md
      - user-guide/getting-started.md
      - user-guide/installation.md
  - Python Api:
      - python-api/index.md
      - python-api/point.md
      - python-api/cell.md
      - python-api/library.md
      - python-api/typings.md
      - Elements:
          - python-api/elements/reference.md
          - python-api/elements/path.md
          - python-api/elements/polygon.md
          - python-api/elements/text.md
  - Development:
      - development/index.md
      - Contributing:
          - development/contributing/git-standards.md
          - development/contributing/index.md
          - development/contributing/ide-configuration.md
          - development/contributing/code-style.md

theme:
  name: material
  locale: en
  palette:
    scheme: slate
    primary: teal
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            docstring_section_style: list
            show_source: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            annotations_path: source
            show_bases: false
            members_order: source
            show_if_no_docstring: true
            show_root_full_path: true
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
