[release]
current-version = "0.0.1-alpha.1"

version-files = [
    "crates/gdsr/Cargo.toml",
    "crates/gdsr-viewer/Cargo.toml",
]

commit-message = "Release v{version}"
branch-name = "release/v{version}"
push = true
confirm = true

[changelog.section-labels]
"Bug Fixes" = ["bug"]
"Library" = ["library"]
"Performance" = ["performance"]
"IO" = ["io"]
"Geometry" = ["geometry"]
"GDS Spec" = ["gds-spec"]
"Viewer" = ["viewer"]
"CLI" = ["cli"]
"Testing" = ["testing"]
"Validation" = ["validation"]
"Documentation" = ["documentation"]

[changelog]
ignore-contributors = ["dependabot[bot]"]
ignore-labels = ["Internal", "ci", "release", "wontfix", "good first issue", "help wanted", "duplicate", "needs-decision", "breaking-change", "dependencies"]
include-contributors = true
changelog-heading = "{version}"
