name: Question
description: Ask a question about GDSR
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: What version of GDSR are you using?
      placeholder: e.g., GDSR 0.1.0
    validations:
      required: false
