name: '✨ Feature request'
description: Suggest a new feature or enhancement for gdsr.
title: '✨ [FEATURE] - <title>'
labels: [enhancement]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Describe the feature or enhancement and explain why it should be implemented.
        Include a code example if applicable.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: >
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: >
        What type of feature is this?
    options:
      - New feature
      - Enhancement
    validations:
      required: true
