FROM ghcr.io/codespaces/macOS:latest

RUN brew install python@3.12

WORKDIR /usr/src/app

COPY requirements-dev.txt .

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir -r requirements-dev.txt

COPY . .

CMD ["bash"]
