name: Lint Python

on:
  pull_request:
    paths:
      - 'gdsr/**'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1
        with:
          src: gdsr/
          args: check

      - uses: chartboost/ruff-action@v1
        with:
          src: gdsr/
          args: format

  mypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install mypy

      - name: Run mypy
        run: |
          source .venv/bin/activate
          mypy gdsr

  isort:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install isort

      - name: Run isort
        run: |
          source .venv/bin/activate
          isort gdsr
