name: Test Python

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv .venv
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            .venv\Scripts\activate
          else
            source .venv/bin/activate
          fi
          pip install -r requirements-test.txt maturin

      - name: Build the gdsr package
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            .venv\Scripts\activate
          else
            source .venv/bin/activate
          fi
          maturin develop

      - name: Run tests
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            .venv\Scripts\activate
          else
            source .venv/bin/activate
          fi
          pytest -n auto
