name: Test Python

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment
        run: |
          python -m venv .venv
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV
          echo "PATH=$GITHUB_WORKSPACE/.venv/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -r requirements-test.txt maturin

      - name: Build the gdsr package
        run: |
          maturin develop

      - name: Run tests
        run: |
          pytest -n auto
