name: Test Python

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment
        run: |
          python -m venv .venv

      - name: Install dependencies
        run: |
          uv pip install -r requirements-test.txt maturin

      - name: Build the pyo3 extension
        run: maturin develop

      - name: Run tests
        run: pytest -n auto
