name: Test, lint, and format

on: [pull_request, workflow_dispatch]

jobs:
  linux-macos-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.11', '3.12']
    name: Test for ${{ matrix.python-version }} on ${{ matrix.os }}
    uses: ./.github/workflows/build-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  windows-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12']
    name: Test for ${{ matrix.python-version }} on windows-latest
    uses: ./.github/workflows/build-test.yml
    with:
      os: windows-latest
      python-version: ${{ matrix.python-version }}
