name: Test Python

on:
    pull_request:
        paths:
            - "gdsr/**"
            - "src/**"
            - "tests/**"
        types:
            - opened
            - synchronize

jobs:
    test-python:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.10", "3.12"]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Create virtual environment
              run: |
                  python -m venv .venv

            - name: Install dependencies
              run: |
                  pip install uv
                  uv pip install -r requirements-test.txt

            - name: Build wheels
              uses: PyO3/maturin-action@v1
              with:
                  command: develop

            - name: Run tests
              run: |
                  if [ ${{ matrix.os }} == 'windows-latest' ]; then
                    .venv\\Scripts\\activate
                    .venv\\Scripts\\pytest -n auto
                  else
                    source .venv/bin/activate
                    pytest -n auto
                  fi
              shell: bash
